host: "localhost"
port: 5432
user: "yourusername"
password: "yourpassword"
dbname: "yourdbname"

messages:
  response:
    start: "Hello! Finally... Did you decide to track your expense?"
    already_authorized: "You have already been authorized."
    unknown_command: "Unknown command. Check if you did a typo."
    expense_saved: "Expense has been savedğŸ‘ŒğŸ»"
    expense_category: "What is category of your expense?"
    expense_money_cost: "What is cost of your expense?"
  error:
    default: "Error was occurred."
    unable_to_save: "Unable to save. Please, try again..."
    unable_to_parse: "Unable to parse. Please, check what you typed..."
    unable_to_reach_session: "Unable to reach user's session. Something went wrong..."